config/routes.rb
Obra::Application.routes.draw do
  devise_for :users

  root 'home#index'

  match "/home/comics" => "home#comics", via: [:get]

  resources :users do
    resources :portfolios, only: [:index] do
      collection do
        get 'list'
      end
    end
  end

  resources :comics do
    resources :readers, only: [:index]
    collection do
      get 'free'
      post :sort
    end

    resources :comic_chapters do
      resources :comic_images
    end
  end

  namespace :api do
    resources :comics do
      collection do
        get 'free'
      end

      resources :comic_chapters do
        resources :comic_images
      end
    end
  end
end

app/models/comic.rb
class Comic < ActiveRecord::Base
  include Concerns::Comic::JsonBuilder
  has_many :comic_chapters, dependent: :destroy
  has_many :feedbacks, dependent: :destroy
  belongs_to :user

  accepts_nested_attributes_for :comic_chapters, reject_if: :all_blank, allow_destroy: true

  scope :comics_of, lambda {|artist_id| where(user_id: artist_id)}
  scope :hottest, lambda { |bench| where('no_likes > ?', bench)}
  scope :new_realease, lambda{|start_date,end_date| where('date >= ? and date <= ?',start_date,end_date)}
  scope :recent_updates, lambda{|start_date,end_date| where('update_chapter >= ? and update_chapter <= ?',start_date,end_date)}

  CATEGORIES = {
      1 => 'Comedy',
      2 => 'Horror',
      3 => 'Action',
      4 => 'Adventure',
      5 => 'Romance',
      6 => 'History'
  }


  def cover_photo
    comic_chapters.first.comic_images.where(cover_photo: true).first.try(:comic)
  end

  validates_presence_of :user_id, :date, :title, :synopsis

end

app/models/comic_chapter.rb
class ComicChapter < ActiveRecord::Base
  belongs_to :comic
  has_many :comic_images,  dependent: :destroy
end

app/models/comic_image.rb
class ComicImage < ActiveRecord::Base

  default_scope { order('position asc') }
  belongs_to :comic_chapter, dependent: :destroy

  acts_as_list

  has_attached_file :comic, styles: {medium: "300x300#", large: "500x500#"}
  validates_attachment_content_type :comic, :content_type => ["image/jpg", "image/jpeg", "image/png"]

end

app/models/concerns/comic/json_builder.rb
module Concerns
  module Comic
    module JsonBuilder
      extend ActiveSupport::Concern

      def custom_hash
        json = attributes
        json["cover"] = cover_photo
        json["medium_cover"] = cover_photo.present? ? cover_photo.url(:medium) : ''
        json
      end
    end
  end
end

app/models/concerns/user/json_builder.rb
module Concerns
  module User
    module JsonBuilder
      extend ActiveSupport::Concern

      def custom_hash
        json = attributes
        json['photo'] = self.pic.url
        json['name'] = name
        json['birthday'] = birthday.try(:strftime,'%m/%d/%Y')
        json['total_likes'] = total_likes
        json
      end
    end
  end
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  belongs_to :comic

  scope :likes, lambda {|comic| where(comic_id: comic, type: 'like')}
  scope :comments, lambda {|comic| where(comic_id: comic, type: 'comment')}
  scope :ratings, lambda {|comic| where(comic_id: comic, type: 'rating')}

  after_save :add_likes

  def add_likes
    if type.eql?('like')
      comic.likes = comic.likes + 1
      comic.save
    end
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  include Concerns::User::JsonBuilder

  has_many :comics

  has_attached_file :pic
  validates_attachment_content_type :pic, :content_type => ["image/jpg", "image/jpeg", "image/png"]

  def total_likes
    comics.sum(:no_likes)
  end

  def name
    [firstname, lastname].join(' ')
  end
end

app/controllers/api/comics_controller.rb
class Api::ComicsController < ApplicationController
  skip_before_filter :authenticate_user!

  def show
    comic = Comic.find params[:id]
    render json: { comic: comic.custom_hash }
  end

  def create

  end

  def destroy

  end

  def free
    comics = Comic.all
    render json: { comics: comics.map(&:custom_hash)  }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!

  layout :layout_by_resource

  def layout_by_resource
    devise_controller? ? 'home' : 'application'
  end

  def after_sign_in_path_for(resource)
    user_portfolios_path(resource)
  end
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  skip_before_filter :authenticate_user!, only: [:show]
  # before_filter :get_comic, except: [:new,:create]
  before_filter :get_comic, except: [:new,:create, :sort, :free]

  layout 'home' , except: [:free]


  def show

  end

  def new
    @comic = Comic.new
  end

  def create
    @comic = Comic.new(comic_params)
    if @comic.save
      if params[:comic][:comic_chapters_attributes].present?
        d = params[:comic][:comic_chapters_attributes].first
        files = d[1][:comic_image]
        chap_id = @comic.comic_chapters.first
        i = 1
        files.each do |img|
          cmg = ComicImage.new
          cmg.comic_chapter = chap_id
          cmg.comic = img
          cmg.cover_photo = true if i.eql?(1)
          cmg.save
          i += 1
        end
      end
    else
      render 'new'
    end
    redirect_to edit_comic_path(@comic)
  end

  def edit
  end

  def update
    @comic.update_attributes!(comic_params)
    redirect_to user_portfolios_path(@comic.user)
  end

  def destroy
    @comic.destroy
  end

  def sort
    params[:comic_image].each_with_index do |id, index|
      ComicImage.where(id: id).update_all(position: index+1, cover_photo: index.eql?(0))
    end
    render nothing: true
  end

  private

  def get_comic
    @comic = Comic.find params[:id]
  end

  def comic_params
    params[:comic][:category] = params[:comic][:category].join(',')  if params[:comic][:category].present?
    params.require(:comic).permit(:title, :synopsis, :downloadable, :user_id, :date, :category, comic_chapters_attributes: [:id, :title, :_destroy])
  end

end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  skip_before_filter :authenticate_user!

  def index
    start_date = Date.today.beginning_of_week
    end_date = Date.today.end_of_week
    def_com = Comic.limit(10)
    @hots = Comic.hottest(20)
    @new_realease = Comic.new_realease(start_date,end_date)
    @updates = Comic.recent_updates(start_date,end_date)
    @hots = def_com if @hots.empty?
    @new_realease = def_com if @new_realease.empty?
    @updates = def_com if @updates.empty?
    @random_cover_photos = Comic.all.sample(4)
    render layout: "home"
  end

  def comics
    start_date = Date.today.beginning_of_week
    end_date = Date.today.end_of_week
    def_com = Comic.limit(10)
    @hots = Comic.hottest(20)
    @new_realeases = Comic.new_realease(start_date,end_date)
    @updates = Comic.recent_updates(start_date,end_date)
    @hots = def_com if @hots.empty?
    @new_realease = def_com if @new_realease.blank?
    @updates = def_com if @updates.empty?
    @random_cover_photos = Comic.all.sample(4)

    render json: {hot: @hots.first.custom_hash, new_realease: @new_realeases.first.custom_hash, recently_updated: @updates.first.custom_hash, random_cover_photo: @random_cover_photos.first.custom_hash}
  end

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController

  def index
    @comics = Comic.comics_of(params[:user_id])
    @user = User.find params[:user_id]

  end

  def list
  	@comics = Comic.comics_of(params[:user_id])
    @user = User.find params[:user_id]
    render json: {comics: @comics.map(&:custom_hash), user: @user.custom_hash}
  end


end

app/controllers/readers_controller.rb
class ReadersController < ApplicationController
	skip_before_filter :authenticate_user!
	layout "home"
	def index
    @comics = Comic.find(params[:comic_id]).comic_chapters.first.comic_images
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def nav_item(name, path)
    	if current_page?(path)
       		@title = name
     	end
    	content_tag('li', :class=>(current_page?(path) ? 'active' : nil) ){link_to(name,path)}
	end
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/readers_helper.rb
module ReadersHelper
end

app/views/comics/_comic_chapter_fields.html.haml
.nested-fields
  .field
    %label Chapter Title
    %br
    = f.text_field :title

  .field
    %label Comics Image
    = f.file_field 'comic_image', multiple: true

app/views/comics/_form.html.haml
= form_for @comic do |f|
  = f.hidden_field :user_id, value: current_user.id
  = f.hidden_field :date, value: Date.today
  .field
    = f.label :title
    %br
    = f.text_field :title
  .field
    = f.label :synopsis
    %br
    = f.text_area :synopsis
  - Comic::CATEGORIES.each do |key,val|
    .field
      = check_box_tag "comic[category][]", key
      %label #{val}

  #comic_chapters
    = f.fields_for :comic_chapters, html: {multipart: true} do |chapter|
      = render 'comic_chapter_fields', :f => chapter
    .links.btn.btn-primary
      = link_to_add_association 'add Chapter', f, :comic_chapters, class:"add-chapter"
  %br
  = f.submit class:"btn btn-primary"

app/views/comics/edit.html.haml
.container-fluid  
  %h3 Edit Comics
  = form_for @comic do |f|
    .field
      = f.label :title
      %br
      = f.text_field :title
    .field
      = f.label :synopsis
      %br
      = f.text_area :synopsis
    - Comic::CATEGORIES.each do |key,val|
      .field
        - if !@comic.category.blank? and @comic.category.include?(key.to_s)
          = check_box_tag "comic[category][]", key , checked: true
        - else
          = check_box_tag "comic[category][]", key
      %label #{val}

    = f.submit class:"btn btn-primary"
    %h5 Drag the pictures for sorting (horizontal order(1,2,3))
    %h3 Chapters
    -@comic.comic_chapters.each do |chapter|
      %hr
      .clear
      .chapters
        %h4 #{chapter.title}
        %ul{class: 'comic_page', style: {cursor: 'move'}, 'data-update-url' => sort_comics_url}
          - chapter.comic_images.each do |cim|
            = content_tag_for :li, cim do
              %image{src: cim.comic}

app/views/comics/free.html.haml
.row
  .span11.wall
    .hero-unit
      %h1 Free comics

    .list
      .section-header
        %div Recommended Freebies
      .list-content
        .node
          %a.imgLink(href="")
            %img(src="https://dcomixologyssl.sslcs.cdngc.net/c/JAN120485_1.jpg?h=f53ec2d5a223d6af2b77f9aea88a4261&amp;width=180")
          .btn.btn-primary Read
          %a.textLink
            .name Saga #1
        .node
          %a.imgLink(href="https://www.comixology.com/Saga-1/digital-comic/22207")
            %img(src="https://dcomixologyssl.sslcs.cdngc.net/c/AUG031264_1.jpg?h=3fb48f94f60b0c4ffaa2748639c0ef8b&width=180")
          .btn.btn-primary Read
          %a.textLink
            .name The Walking Dead
        .node
          %a.imgLink(href="https://www.comixology.com/Saga-1/digital-comic/22207")
            %img(src="https://dcomixologyssl.sslcs.cdngc.net/c/MAR100199.jpg?h=339da139e446823f916db71ab76169fb&width=180")
          .btn.btn-primary Read
          %a.textLink
            .name Superman: War of the Supermen #0
        .node
          %a.imgLink(href="https://www.comixology.com/Saga-1/digital-comic/22207")
            %img(src="https://dcomixologyssl.sslcs.cdngc.net/c/DIG009455_1.jpg?h=a8e7cbd7719d8ead2dc28a4db404b7cc&width=180")
          .btn.btn-primary Read
          %a.textLink
            .name Darkstalkers
        .node
          %a.imgLink(href="https://www.comixology.com/Saga-1/digital-comic/22207")
            %img(src="https://dcomixologyssl.sslcs.cdngc.net/c/DIG014107_2.jpg?h=ecf679614413f6515a2cb484ad42270a&width=180")
          .btn.btn-primary Read
          %a.textLink
            .name Stray Bullets
        .node
          %a.imgLink(href="https://www.comixology.com/Saga-1/digital-comic/22207")
            %img(src="https://dcomixologyssl.sslcs.cdngc.net/c/DEC980201.jpg?h=a0dcd9b60358c81a2fd30741f5d9b800&amp;width=180")
          .btn.btn-primary Read
          %a.textLink
            .name Planetary #1
        .node
          %a.imgLink(href="https://www.comixology.com/Saga-1/digital-comic/22207")
            %img(src="https://dcomixologyssl.sslcs.cdngc.net/c/DIG008483_2.jpg?h=3e9b5d899410a0d6606a3bae47f00baf&width=180")
          .btn.btn-primary Read
          %a.textLink
            .name Sex Criminals


        .node
          %a.imgLink(href="https://www.comixology.com/Saga-1/digital-comic/22207")
            %img(src="https://dcomixologyssl.sslcs.cdngc.net/c/JAN120485_1.jpg?h=f53ec2d5a223d6af2b77f9aea88a4261&amp;width=180")
          .btn.btn-primary Read
          %a.textLink
            .name Saga #1
        .node
          %a.imgLink(href="https://www.comixology.com/Saga-1/digital-comic/22207")
            %img(src="https://dcomixologyssl.sslcs.cdngc.net/c/AUG031264_1.jpg?h=3fb48f94f60b0c4ffaa2748639c0ef8b&width=180")
          .btn.btn-primary Read
          %a.textLink
            .name The Walking Dead
        .node
          %a.imgLink(href="https://www.comixology.com/Saga-1/digital-comic/22207")
            %img(src="https://dcomixologyssl.sslcs.cdngc.net/c/MAR100199.jpg?h=339da139e446823f916db71ab76169fb&width=180")
          .btn.btn-primary Read
          %a.textLink
            .name Superman: War of the Supermen #0
        .node
          %a.imgLink(href="https://www.comixology.com/Saga-1/digital-comic/22207")
            %img(src="https://dcomixologyssl.sslcs.cdngc.net/c/DIG009455_1.jpg?h=a8e7cbd7719d8ead2dc28a4db404b7cc&width=180")
          .btn.btn-primary Read
          %a.textLink
            .name Darkstalkers
        .node
          %a.imgLink(href="https://www.comixology.com/Saga-1/digital-comic/22207")
            %img(src="https://dcomixologyssl.sslcs.cdngc.net/c/DIG014107_2.jpg?h=ecf679614413f6515a2cb484ad42270a&width=180")
          .btn.btn-primary Read
          %a.textLink
            .name Stray Bullets
        .node
          %a.imgLink(href="https://www.comixology.com/Saga-1/digital-comic/22207")
            %img(src="https://dcomixologyssl.sslcs.cdngc.net/c/DEC980201.jpg?h=a0dcd9b60358c81a2fd30741f5d9b800&amp;width=180")
          .btn.btn-primary Read
          %a.textLink
            .name Planetary #1
        .node
          %a.imgLink(href="https://www.comixology.com/Saga-1/digital-comic/22207")
            %img(src="https://dcomixologyssl.sslcs.cdngc.net/c/DIG008483_2.jpg?h=3e9b5d899410a0d6606a3bae47f00baf&width=180")
          .btn.btn-primary Read
          %a.textLink
            .name Sex Criminals

app/views/comics/new.html.haml
.container-fluid
	%h3 New Comic
	= render "form"

app/views/home/_slider.html.haml
.slider-wrapper.theme-dark
  #slider.nivoSlider
    - @random_cover_photos.each do |foto| 
      %img{alt: "", "data-thumb" => "images/up.jpg", src: foto.cover_photo, title: "This is an example of a caption"}/
  #htmlcaption.nivo-html-caption
    %strong This
    is an example of a
    %em HTML
    caption with
    = succeed "." do
      %a{href: "#"} a link

app/views/home/index.html.haml
.container-fluid
  = render "slider"
  .ribbon
    WHAT'S HOT
  %br/
  %br/
  .slider1
    - @hots.each do |hot|
      .slide
        = link_to comic_path(hot) do
          %img{src: hot.cover_photo}/
  %br/
  %br/
  .ribbon
    NEW RELEASES
  %br
  %br
  .slider1
    - @new_realease.each do |new_release|
      .slide
        = link_to comic_path(new_release) do
          %img{src: new_release.cover_photo}/
  %br/
  .ribbon
    RECENTLY UPDATED
  %br/
  %br/
  .slider1
    - @updates.each do |up|
      .slide
        = link_to comic_path(up) do
          %img{src: up.cover_photo}/
  %br/

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Obra
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = render :partial => "/shared/nav"
    .container.wrapper
      = yield
    = render :partial => "/shared/footer"

app/views/layouts/application.html.slim
doctype 5
html
  head
    title Obra
    meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
    = stylesheet_link_tag    "application", media: "all"
    = csrf_meta_tags
    
  = render :partial => "/shared/nav"
  .container.wrapper
    body data-ng-app="obra"
      div data-ng-view=""


  = javascript_include_tag "application"

app/views/layouts/home.html.haml
!!!
%html
  %head
    %title Obra
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = render :partial => "/shared/nav"
    .container.wrapper
      = yield
    / = render "/shared/footer"

app/views/portfolios/index.html.haml
-# .container-fluid
-#   .row.profiler
-#     .span2
-#       %img{src: @user.pic,class:"img-polaroid"}
-#     .span4
-#       %table
-#         %tr
-#           %td{width:"60%"}
-#             Name
-#           %td
-#             = "#{@user.firstname} #{@user.lastname}"
-#         %tr
-#           %td{width:"50%"}
-#             Contact No:
-#           %td
-#             = @user.contact_no
-#         %tr
-#           %td{width:"55%"}
-#             Birthday
-#           %td
-#             = @user.birthday.try(:strftime, '%m/%d/%Y')
-#         %tr
-#           %td{width:"60%"}
-#             Likes received
-#           %td
-#             = @user.total_likes
-#   %hr
  
-#     %b MY COMIC STAND
-#     %br
-#     %br
-#     - @comics.each do |comic|
-#       .row.profiler
-#         .span2
-#           %img{src:"/assets/sample.jpg",class:"img-polaroid"}
-#         .span4
-#           %h4
-#             TITLE GOES HERE
-#           %p
-#             Some description here....
-#     .row.profiler
-#       .span2
-#         %img{src:"/assets/sample.jpg",class:"img-polaroid"}
-#       .span4
-#         %h4
-#           TITLE GOES HERE
-#         %p
-#           Some description here....
-#         %span
-#           79 comments
-#           %img{src:"/assets/comment-icon.png"}
-#           | 
-#           29 likes
-#           %img{src:"/assets/star.png"}
-#     %br

-#     .row.profiler
-#       .span2
-#         %img{src:"/assets/sample.jpg",class:"img-polaroid"}
-#       .span4
-#         %h4
-#           TITLE GOES HERE
-#         %p
-#           Some description here....
-#         %span
-#           99 comments
-#           %img{src:"/assets/comment-icon.png"}
-#           | 
-#           24 likes
-#           %img{src:"/assets/star.png"}
    


-#   - if current_user.eql?(@user)
-#     = link_to 'New Comic', new_comic_path

app/views/readers/index.html.haml
#myCarousel.carousel.slide
  %ol.carousel-indicators
    %li.active{"data-slide-to" => "0", "data-target" => "#myCarousel"}
    %li{"data-slide-to" => "1", "data-target" => "#myCarousel"}
    %li{"data-slide-to" => "2", "data-target" => "#myCarousel"}
  / Carousel items
  .carousel-inner
    - @comics.each_with_index do |img,i|
      .item{class: "#{i.eql?(0) ? 'active' : ''}", style: "background-color: #000000"}
        %center
          %image{src: img.comic.url(:original)}
  / Carousel nav
  %a.carousel-control.left{"data-slide" => "prev", href: "#myCarousel"} ‹
  %a.carousel-control.right{"data-slide" => "next", href: "#myCarousel"} ›

app/views/shared/_footer.html.haml
#footer
  .container
    %p.muted.credit
      Example courtesy
      %a{href: "http://martinbean.co.uk"} Martin Bean
      and
      = succeed "." do
        %a{href: "http://ryanfait.com/sticky-footer/"} Ryan Fait

app/views/shared/_nav.html.haml
.navbar.navbar-default.navbar-fixed-top
  .navbar-inner
    .container
      %button.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse", type: "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.brand{href: root_path}
        %img.logo{src: "/assets/logo.png"}/
      .nav-collapse.collapse
        %ul.nav.menu
          %li.active
            = nav_item "Home", root_path
          - if !user_signed_in?
            %li
              = nav_item "Join our community", new_user_registration_path
          
          
          %li
            - if user_signed_in?
              = link_to "Log out", destroy_user_session_path, method: :delete, confirm:"Are you sure?"
            - else
              = nav_item "Log in", new_user_session_path
              / = nav_item "Login", user_session_path
          %li
            = link_to "Browse Comics", free_comics_path
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
              Categories
              %b.caret
            %ul.dropdown-menu
              %li
                %a{href: "#"} Action
              %li
                %a{href: "#"} Another action
              %li
                %a{href: "#"} Something else here
              %li.divider
              %li.nav-header Nav header
              %li
                %a{href: "#"} Separated link
              %li
                %a{href: "#"} One more separated link
          %li.search-works
            %form.form-search
              / .input-append
              %input.span3.search-query{type: "text", placeholder:"Discover some works"}/
              / %button.btn{type: "submit"}
              /   %i.icon-home
          - if user_signed_in?
            %li
              = nav_item "My Works", user_portfolios_path(current_user)

      / /.nav-collapse